name: Tauri Release

on:
  push:
    branches:
      - develop
    paths:
      - 'toke-tauri/**'
      - 'main.go'
      - 'internal/**'
      - 'go.mod'
      - 'go.sum'
      - 'VERSION'
    tags:
      - 'v*'
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-tauri:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin' || '' }}


      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build toke binary (macOS)
        if: runner.os == 'macOS'
        run: |
          echo "Building toke binary to build/toke-darwin-arm64/toke"
          go build -o "build/toke-darwin-arm64/toke" .

      - name: Get VERSION
        id: get_version
        shell: bash
        run: |
          VERSION=$(cat VERSION)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Update Tauri version (macOS)
        if: runner.os == 'macOS'
        run: |
          sed -i '' "s/\"version\": \".*\"/\"version\": \"${{ steps.get_version.outputs.version }}\"/" toke-tauri/src-tauri/tauri.conf.json
          echo "Updated tauri.conf.json:"
          grep '"version"' toke-tauri/src-tauri/tauri.conf.json

      - name: Install Tauri dependencies
        working-directory: ./toke-tauri
        run: npm install

      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          projectPath: './toke-tauri'
          args: ${{ matrix.args }}
          includeUpdaterJSON: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: toke-tauri-${{ matrix.platform }}
          path: |
            toke-tauri/src-tauri/target/release/bundle/dmg/*.dmg
            toke-tauri/src-tauri/target/release/bundle/macos/*.app.tar.gz
            toke-tauri/src-tauri/target/release/bundle/macos/*.app.tar.gz.sig

  release:
    needs: build-tauri
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' && github.ref == 'refs/heads/develop') || startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version from VERSION file
        id: get_version
        run: |
          # Read version from VERSION file
          VERSION=$(cat VERSION)
          echo "Version from file: $VERSION"
          
          # Add 'v' prefix for tag
          NEW_VERSION="v${VERSION}"
          
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "Tag version: $NEW_VERSION"

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          name: "Toke Desktop ${{ steps.get_version.outputs.version }}"
          body: |
            ## Toke Desktop Release
            
            **Version:** ${{ steps.get_version.outputs.version }}
            **Commit:** ${{ github.sha }}
            
            ### Changes
            ${{ github.event.head_commit.message }}
            
            ### Downloads
            - **macOS**: Download the `.dmg` file for macOS
          files: |
            toke-tauri-*/**/*.dmg
            toke-tauri-*/**/*.app.tar.gz
            toke-tauri-*/**/*.app.tar.gz.sig
            toke-tauri-*/**/latest.json
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}